const data = {
  products: [
    {
      name: 'Free Shirt',
      slug: 'free-shirt',

      category: 'Shirts',
      image: '/images/shirt1.jpg',
      price: 70,
      Brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Fit Shirt',
      category: 'Shirts',
      slug: 'fit-shirt',
      image: '/images/shirt2.jpg',
      price: 80,
      Brand: 'Adidas',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Formal Shirt',
      slug: 'formal-shirt',
      category: 'Shirts',
      image: '/images/shirt3.jpg',
      price: 60,
      Brand: 'Raymond',
      rating: 4.7,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Golf Pants',
      slug: 'golf-pants',
      category: 'Pants',
      image: '/images/pants1.jpg',
      price: 90,
      Brand: 'Wrangler',
      rating: 4.6,
      numReviews: 10,
      countInStock: 20,
      description: 'Slim fit pants',
    },
    {
      name: 'Fit Pants',
      slug: 'fit-pants',
      category: 'Pants',
      image: '/images/pants2.jpg',
      price: 95,
      Brand: 'Zara',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A regular pant',
    },
    {
      name: 'Classic pants',
      slug: 'classic-pants',
      category: 'Pants',
      image: '/images/pants3.jpg',
      price: 70,
      Brand: 'Arrow',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular pant',
    },
  ],
};
export default data;
